export { default as GuestHome } from './guest-home/guest-home'
export { default as Login } from './login/login'
export { default as AdvisorHome } from './advisor-home/advisor-home'
export { default as AdvisorTeacherManagement } from './advisor-teacher-management/advisor-teacher-management'
export { default as AdvisorStudentManagement } from './advisor-student-management/advisor-student-management'
export { default as AdvisorDisciplineManagement } from './advisor-discipline-management/advisor-discipline-management'
export { default as TeacherHome } from './teacher-home/teacher-home'
